# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Fábio Rogério SJ
subtitle: Endoidecido por tecnologia :)
description: Estudando a um bom tempo tecnologias posso dizer que acredito que o mundo pode ser mudado e moldado pela tecnologia!
author: Fábio Rogério SJ
language: pt
timezone: America/Sao_Paulo

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://fabiorogeriosj.com.br
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

#Custom Setting Start

# Site settings
SEOTitle: Fábio Rogério SJ | Blog
header-img: img/back.jpg
email: fabio.rogerio.sj@gmail.com
keyword: ""


# SNS settings
# RSS: false
github_username:    fabiorogeriosj
twitter_username:   fabiorogeriosj
facebook_username:  fabiorogeriosj
linkedin_username:  fábio-rogério-sj-4a49b722

# Build settings
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`


# Disqus settings
disqus_username: fabiorogeriosj

# Duoshuo settings
# duoshuo_username: kaijun
# Share component is depend on Comment so we can NOT use share only.
duoshuo_share: true                     # set to false if you want to use Comment without Sharing


# Analytics settings
# Google Analytics
ga_track_id: 'UA-12168350-1'            # Format: UA-xxxxxx-xx
ga_domain: fabiorogeriosj.com.br


# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "Fábio Rogério da Silva José​, conhecido como Fábio Rogério SJ nas redes sociais, é desenvolvedor de aplicações web e mobile desde quando o Internet Explorer 7 erá um pesadelo e desenvolver aplicativos híbridos com tecnologias web era um trabalho árduo, ou seja, desde 2007."
sidebar-avatar: img/avatar.png      # use absolute URL, seeing it's used in both `/` and `/about/`


# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value


# Friends
friends: [
    {
        title: "MobileUI",
        href: "https://mobileui.github.io"
    },
    {
        title: "Ionic Framework",
        href: "http://ionicframework.com"
    },
    {
        title: "ngCordova",
        href: "http://ngCordova.com"
    },
    {
        title: "Apache Cordova",
        href: "https://cordova.apache.org/"
    }
]


#Custom Setting End

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:
  - lab/education_br.html

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: DD/MM/YYYY
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: huxblog

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: https://github.com/fabiorogeriosj/fabiorogeriosj.github.io.git
